- dockci/models/build.py
Merge doesn't make much sense without this PR: https://github.com/RickyCook/DockCI/pull/4
https://trello.com/c/mAT54G5q
> Add a tag in docker if build is a tagged version

- README.md
> Adding ubuntu howto, to README.md

- dockci/models/build.py
Test suite would probably have saved me there.
New card: https://trello.com/c/tuxVCP8z
> Fix logic bug introduced in c632d38d

- CHANGELOG.md
- Makefile
- bower.json
- dockci/templates/_base.html
https://trello.com/c/rui7ehfT/70-gravatars-for-author-committer
> Add git author/committer gravatars

- CHANGELOG.md
- dockci/templates/_base.html
- dockci/templates/config_edit.html
- dockci/views/core.py
Make check boxes use the material design theme, conform better with material design standards
> Material design check boxes

- .travis.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- dockci/models/build.py
- dockci/templates/job.html
Filter builds for only version tagged, successful builds (the kind that you'd want to release, or use in service provisioning)
> Job release filter

- CHANGELOG.md
- dockci/models/build.py
- dockci/models/job.py
- dockci/templates/build.html
- dockci/templates/build_new.html
- dockci/templates/job.html
- dockci/views/build.py
It would be useful to be able to specify tag names instead of hash ID's
to kick off builds.
https://trello.com/c/cs4TkIdT
> Take a tag reference instead of a hash

- CHANGELOG.md
- dockci/models/build.py
https://trello.com/c/FlA3lSnZ/30-bug-command-invocation-cwd-below-output-in-log
> Command output out of order

- CHANGELOG.md
- dockci/templates/build.html
https://trello.com/c/k08f4wuh/73-roll-up-build-stages
> Roll up build stage panel detail on click

- dockci/templates/build.html
https://trello.com/c/yO6HheDl/72-bug-new-lines-in-log-are-not-displayed
> Add nbsp to empty log div

- CHANGELOG.md
- dockci/views/build.py
- dockci/views/job.py
https://trello.com/c/6JWzkRvZ/74-bug-404-on-objects-not-found
> 404 on objects that don't exist

- CHANGELOG.md
- dockci/migrations/0002.py
- dockci/models/build.py
- dockci/models/config.py
- dockci/templates/config_edit.html
- dockci/util.py
- dockci/views/core.py
https://trello.com/c/5waQLrYl/80-multiple-docker-hosts
> Multiple docker hosts

- dockci/views/core.py
https://trello.com/c/DPzeRiI9/83-bug-no-config-on-new-instance-raises-http-500
> Ignore config load failure

- README.md
> Update README to make Debian default OS

- CHANGELOG.md
- dockci/server.py
- dockci/templates/_base.html
- dockci/templates/build.html
- dockci/templates/config_edit.html
- dockci/views/test.py
> Add server tests for the docker registry

- CHANGELOG.md
- dockci/templates/job_edit.html
- dockci/views/external.py
> Iteratively load projects until end

- CHANGELOG.md
- dockci/migrations/0004.py
- dockci/models/build.py
- dockci/models/build_meta/stages_prepare.py
- dockci/models/project.py
- dockci/server.py
- dockci/templates/build.html
- dockci/templates/build_new.html
- dockci/templates/index.html
- dockci/templates/project.html
- dockci/templates/project_edit.html
- dockci/views/build.py
- dockci/views/core.py
- dockci/views/project.py
- dockci/workers.py
> Rename job to project

- CHANGELOG.md
- dockci/migrations/0006.py
- dockci/models/job.py
- dockci/models/job_meta/stages_post.py
- dockci/templates/_base.html
> Rename "error" build state to "broken"

- CHANGELOG.md
- Makefile
- dockci/models/job.py
- dockci/models/project.py
- dockci/templates/_base.html
- dockci/templates/config_edit.html
- dockci/templates/project.html
- dockci/util.py
- dockci/views/project.py
- requirements.txt
- Delete project YAML itself
- Delete associated job data
- Delete GitHub web hook
- Authenticate forms with HMAC hash
- Fixes untracked issue where project save success message would display on every view
Closes #92
> Delete projects and associated data

- CHANGELOG.md
- dockci/templates/job.html
> Don't roll up log when body is clicked

- CHANGELOG.md
- dockci/migrations/0007.py
- dockci/views/job.py
Fixes #90 
Also fixes untracked issue introduced by #167 that didn't correctly migrate build config meta to job config meta
> Security artifact download path

- CHANGELOG.md
- dockci/views/project.py
> Error when adding a project that already exists

- CHANGELOG.md
- dockci/templates/project.html
- dockci/views/project.py
> Fix getting auth token with anon user

- CHANGELOG.md
- dockci/migrations/0008.py
- dockci/models/project.py
- dockci/templates/project_edit.html
- dockci/views/project.py
> Fix invalid repo name

- CHANGELOG.md
- dockci/models/project.py
- dockci/templates/_base.html
- dockci/templates/index.html
- dockci/templates/project.html
- dockci/views/project.py
> Project shields

- CHANGELOG.md
- dockci/views/project.py
> Redirect on new project

- CHANGELOG.md
- dockci/models/job_meta/stages.py
> Shlex command output, remove CWD

- CHANGELOG.md
- dockci/models/job.py
- dockci/models/job_meta/stages_prepare.py
- dockci/util.py
Add a step to set `mtime` for files with an `ADD` directive in a `Dockerfile`
Fixes #69
> Fix dockerfile cache

- CHANGELOG.md
- dockci/models/job_meta/stages.py
- requirements.txt
> Upgrade docker py

- CHANGELOG.md
- dockci/migrations/0009.py
- dockci/models/project.py
- dockci/templates/index.html
- dockci/templates/project_edit.html
- dockci/util.py
- dockci/views/core.py
- dockci/views/project.py
> Create utility project

- CHANGELOG.md
- dockci/models/job.py
- dockci/models/job_meta/config.py
- dockci/models/job_meta/stages_main.py
- dockci/models/job_meta/stages_prepare.py
- dockci/templates/job.html
> Utility project run

- dockci/models/job.py
- dockci/models/job_meta/stages_main.py
- dockci/models/job_meta/stages_prepare.py
- dockci/templates/job.html
- dockci/util.py
> Utility project add files

- CHANGELOG.md
- dockci/models/job_meta/stages_prepare.py
- dockci/util.py
- dockci/views/job.py
> Utility project retrieve

- CHANGELOG.md
- dockci/migrations/0009.py
- dockci/models/job.py
- dockci/models/job_meta/config.py
- dockci/models/job_meta/stages_main.py
- dockci/models/job_meta/stages_prepare.py
- dockci/models/project.py
- dockci/templates/index.html
- dockci/templates/job.html
- dockci/templates/project_edit.html
- dockci/util.py
- dockci/views/core.py
- dockci/views/job.py
- dockci/views/project.py
> Feature utility project

- CHANGELOG.md
- dockci/models/job_meta/config.py
- dockci/models/job_meta/stages_main.py
- dockci/models/job_meta/stages_prepare.py
> Specify Dockerfile used to build

- CHANGELOG.md
- dockci/exceptions.py
- dockci/models/config.py
- dockci/models/job.py
- dockci/templates/config_edit.html
- dockci/util.py
- tests/test_exceptions.py
- tests/test_util.py
> Docker host certs

- CHANGELOG.md
- dockci/templates/job.html
> Fix infinite loop in stage panels

- CHANGELOG.md
- dockci/handlers.py
> Smtp error without server

- dockci/models/job.py
- dockci/models/project.py
- tests/test_util.py
> Ancestor jobs broken

- dockci/models/job.py
> Switch from SQL time to Python time

- dockci/models/job_meta/stages_prepare.py
- dockci/util.py
- tests/test_util.py
> Fix branch detection

- dockci/api/fields.py
- dockci/api/job.py
> Handle commit ref whitespace

- dockci/api/project.py
- dockci/static/js/components/project_edit.html
- dockci/static/js/models/project.js
> Add missing data binds, and parser args for github_secret

- dockci/commands/gunicorn.py
- dockci/commands/tests.py
- dockci/static/js/components/github_repos_list.js
- dockci/util.py
- docker-compose.yml
Fixes #296 
The mount of local `dockci` code into the container at `/code/dockci` overrides the static that was collected on `docker build`.
> Add collect static to compose boot

- dockci/static/js/components/github_repos_list.js
- dockci/static/js/components/project_edit.html
- dockci/static/js/components/project_edit.js
- dockci/views/external.py
- dockci/views/oauth.py
> Fix GitHub auth redir

- dockci/api/project.py
- dockci/models/job.py
- dockci/models/project.py
- dockci/static/js/components/project_edit.html
- dockci/static/js/components/project_edit.js
- dockci/static/js/models/project.js
- dockci/templates/project.html
> Fix GitHub job status

- CHANGELOG.md
- dockci/models/config.py
- dockci/models/job.py
- dockci/server.py
- dockci/templates/config_edit.html
- dockci/views/core.py
> Fix GitHub status errors

- CHANGELOG.md
- dockci/api/project.py
> Update project slug regex to match Docker

- dockci/models/job.py
- dockci/util.py
- dockci/views/job.py
- tests/test_util.py
> Fix GitHub push ref

- dockci/api/exceptions.py
- dockci/server.py
> Rollbar ignore some exceptions

- CHANGELOG.md
- dockci/util.py
- dockci/views/job.py
> Gitlab web hook

- CHANGELOG.md
- dockci/exceptions.py
- dockci/models/config.py
- dockci/models/job.py
- dockci/models/job_meta/stages.py
- dockci/models/job_meta/stages_post.py
- dockci/templates/config_edit.html
- dockci/templates/job.html
- dockci/util.py
- dockci/views/core.py
> Registry login

- CHANGELOG.md
- dockci/models/config.py
- dockci/server.py
- dockci/templates/config_edit.html
- dockci/views/core.py
- dockci/views/external.py
> Add GitLab auth

- dockci/models/job_meta/stages.py
- dockci/models/job_meta/stages_main.py
- dockci/models/job_meta/stages_prepare.py
- dockci/models/project.py
- tests/models/job_meta/test_stages.py
Closes #326 
Closes #176
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/333)
> Clone private

- CHANGELOG.md
- dockci/api/base.py
- dockci/handlers.py
Fixes #339
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/338)
> Fix api auth

- CHANGELOG.md
- alembic/versions/5773ec3bc06_job_repo_fs.py
- dockci/api/job.py
- dockci/api/project.py
- dockci/models/base.py
- dockci/models/job.py
- dockci/models/job_meta/stages_prepare.py
- dockci/models/project.py
- dockci/static/js/components/job_run_dialog.html
- dockci/static/js/models/project.js
- dockci/templates/job.html
- dockci/views/job.py
- tests/models/job_meta/test_stages.py
- tests/models/test_project_model.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/352)
> WIP Project list fields

- CHANGELOG.md
- dockci/api/job.py
- dockci/api/project.py
- dockci/api/util.py
- dockci/models/job.py
- dockci/models/project.py
- dockci/templates/index.html
- tests/api/test_job_api.py
Adds success, fail, broken totals to project list as per #334
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/354)
> Project list fields

- CHANGELOG.md
- dockci/api/fields.py
- dockci/api/project.py
As per requirement in #334
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/355)
> Add latest_job to projects list api

- CHANGELOG.md
- dockci/models/job_meta/stages_main.py
Fixes #356
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/357)
> Skipped tests are exit_code 0

- CHANGELOG.md
- dockci/models/job_meta/stages_post.py
Fixes #364
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/365)
> Don't clean up image if there isn't one

- dockci/models/job_meta/stages_prepare_docker.py
- dockci/util.py
- tests/test_util.py
Fixes #366
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/367)
> Fix FauxDockerLog with handle, add tests

- dockci/models/job_meta/stages.py
- dockci/models/job_meta/stages_prepare_docker.py
- dockci/util.py
Fixes #348
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/383)
> External services

- CHANGELOG.md
- dockci/models/blob.py
- dockci/models/job_meta/stages_prepare_docker.py
- tests/models/test_blob_model.py
Closes #201
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/388)
> Utility cache

- dockci/static/js/components/job_stage_docker_line.html
- dockci/static/js/components/job_stage_docker_line.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/393)
> Handle docker errors

- CHANGELOG.md
- dockci/models/job.py
- dockci/models/job_meta/stages_post.py
- tests/db/models/test_job_db.py
- tests/models/test_job_model.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/394)
> Informational messages when a build can't be pushed

- dockci/static/js/components/project_edit.html
- dockci/static/js/models/project.js
Fixes #395
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/396)
> Fix non-manual project edit

- CHANGELOG.md
- dockci/static/js/components/git_repo_display.html
- dockci/static/js/components/git_repo_display.js
- dockci/static/js/components/git_user.html
- dockci/templates/_base.html
- dockci/templates/job.html
- dockci/templates/project.html
Closes #81
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/399)
> Link to GitHub if repo is GitHub

- CHANGELOG.md
- dockci/static/js/components/job_stage.html
- dockci/static/js/components/job_stage.js
- dockci/static/js/components/job_stage_build_step.html
- dockci/static/js/components/job_stage_build_step.js
- dockci/templates/job.html
Closes: #370
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/400)
> Build stage folding

- CHANGELOG.md
- dockci/models/job_meta/stages_main.py
- dockci/models/job_meta/stages_prepare_docker.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/401)
> Update util operation IDs

- CHANGELOG.md
- dockci/models/job_meta/stages_prepare_docker.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/402)
> Don't create empty util cache on failure

- CHANGELOG.md
- dockci/api/project.py
- dockci/models/project.py
- tests/db/models/test_project_db.py
Closes #403
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/404)
> Filtered projects summary

- CHANGELOG.md
- dockci/api/job.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/405)
> Add create_ts and commit to jobs list

- CHANGELOG.md
- dockci/templates/_base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/406)
> Detect WSS/WS

- CHANGELOG.md
- dockci/models/project.py
- tests/db/models/test_project_db.py
Fixes #408 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/409)
> Add "incomplete" to projects summary

- CHANGELOG.md
- dockci/api/fields.py
- dockci/api/job.py
- dockci/util.py
Closes #410
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/412)
> Job list avatars

- dockci/api/fields.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/413)
> Account for no email in GravatarUrl field

- CHANGELOG.md
- dockci/api/project.py
Closes #411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/414)
> Add git author gravatar to project latest job

- CHANGELOG.md
- dockci/api/__init__.py
- dockci/api/time.py
Closes #415 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/417)
> Add current time API

- CHANGELOG.md
- dockci/api/project.py
Closes #418
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/419)
> Add slug to latest_job project API

- CHANGELOG.md
- dockci/api/job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/420)
> Add tag, and git_branch to jobs list API

- dockci/api/job.py
- dockci/models/job.py
- dockci/static/js/models/job.js
- dockci/templates/job.html
- dockci/util.py
- dockci/views/job.py
Closes #258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/421)
> Api for live job

- CHANGELOG.md
- dockci/api/user.py
Closes #424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/425)
> Add user gravatar to user API

- CHANGELOG.md
- dockci/models/blob.py
Utilities copy permissions (exec, etc) correctly
Fixes #427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/428)
> Fix utility permissions

- dockci/views/job.py
Closes #429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/430)
> Log init seek lines

- CHANGELOG.md
- dockci/api/config.py
- dockci/handlers.py
- dockci/server.py
- dockci/session.py
- dockci/util.py
- pylint.conf
Closes #435
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/436)
> Api no session

- CHANGELOG.md
- dockci/api/project.py
Closes #437
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/438)
> Recent projects

- CHANGELOG.md
- dockci/api/job.py
Fixes #443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/444)
> Fix job stream with no stages

- CHANGELOG.md
- dockci/views/oauth.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/445)
> Fix oauth redir

- CHANGELOG.md
- dockci/models/config.py
- dockci/templates/config_edit.html
- dockci/views/core.py
- dockci/views/oauth.py
OAuth redirects only for authorized URLs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/451)
> Authorized redirects

- dockci/api/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/452)
> User API creates with security datastore

- CHANGELOG.md
- dockci/api/user.py
- dockci/models/config.py
- dockci/templates/config_edit.html
- dockci/templates/security/login_user.html
- dockci/views/core.py
- Login and registration forms disablable separately
- User API respects disabled registration flag
Fixes #454 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/456)
> Disable login/register

- CHANGELOG.md
- dockci/api/project.py
Fixes #439
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/457)
> Projects recent order includes projects with no jobs

- dockci/models/job.py
Fixes #431
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/458)
> Don't add error stages twice

- CHANGELOG.md
- dockci/api/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/459)
> Correctly change user password with Flask-Security

- CHANGELOG.md
- dockci/api/job.py
- requirements.in
- requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/460)
> Pagination for API jobs list

- dockci/stage_io.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/462)
> Stage io auto encode

- Dockerfile
- _deps_python.sh
- dockci.Dockerfile
- dockci.yaml
- dockci/models/job_meta/stages_prepare.py
- requirements.in
- requirements.txt
Closes #461
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/463)
> Use libgit to find tags

- alembic/versions/289417c9d06_admin_role.py
- dockci/templates/_base.html
- dockci/views/core.py
- Add admin role
- All users migrated for admin role
- Protect config views with admin role
Closes: #468 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/473)
> Admin role

- dockci/api/user.py
Fixes #447
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/474)
> Correctly output user emails

- CHANGELOG.md
- dockci/api/user.py
Read-only part of #471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/475)
> RO roles in user detail

- docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/476)
> Persist db, and registry in compose

- CHANGELOG.md
- dockci/api/user.py
- dockci/util.py
- docker-compose.yml
- tests/conftest.py
- tests/db/api/test_user_api_db.py
- tests/db/test_util_db.py
Closes #471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/477)
> User API for roles

- CHANGELOG.md
- dockci/api/user.py
API to list available roles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/480)
> Roles list api

- dockci/api/user.py
- tests/db/api/test_user_api_db.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/481)
> User roles API sets, rather than adds roles

- CHANGELOG.md
- dockci/static/js/components/config_user_row.html
- dockci/static/js/components/config_user_row.js
- dockci/static/js/components/config_users.html
- dockci/static/js/components/config_users.js
- dockci/static/js/components/tag_pill.html
- dockci/static/js/components/tag_pill.js
- dockci/static/js/components/text_input_completion.html
- dockci/static/js/components/text_input_completion.js
- dockci/static/js/models/role.js
- dockci/static/js/models/user.js
- dockci/templates/config_edit.html
- dockci/views/core.py
Closes #472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/482)
> User management ui

- dockci/api/user.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/483)
> Set user routes endpoint correctly

- dockci/api/jwt.py
- dockci/api/user.py
- dockci/api/util.py
- dockci/handlers.py
- dockci/models/auth.py
- dockci/util.py
- tests/db/api/test_jwt_api_db.py
Closes #469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/484)
> Agent service keys

- CHANGELOG.md
- dockci/api/job.py
- dockci/util.py
- tests/conftest.py
- tests/db/api/test_job_api_db.py
API for agents to update jobs and stages
Closes #470
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/485)
> Agent job api

- CHANGELOG.md
- dockci/api/job.py
Fixes #277 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/486)
> Default exit code in API is null

- dockci/api/job.py
Result field in Job API
Result field accepts `None` as a good value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/487)
> Add result field to job api

- CHANGELOG.md
- dockci/api/job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/488)
> Allow filtering by tag in jobs list

- CHANGELOG.md
- dockci/api/config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/489)
> Agents requesting registries get password

- dockci/api/job.py
- dockci/models/job.py
- dockci/models/project.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/490)
> External service update from api

- dockci/api/fields.py
- dockci/api/job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/492)
> Allow 'now' in API date inputs

- CHANGELOG.md
- dockci/api/job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/493)
> Distinct commits API

- CHANGELOG.md
- dockci/api/job.py
- dockci/models/job.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/494)
> Add commit filter to job API/model

- dockci.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sprucedev/dockci/496)
> New job config format
